class_name NavConstants
extends RefCounted

enum MoveMode { FREE, FORMATION }

const NAVIGATION_TICK_RATE := 20.0
const BLOCKER_REFRESH_SECONDS := 0.5
const ENEMY_BLOCK_SECONDS := 0.4
const FRIENDLY_YIELD_SECONDS := 0.4
const FRIENDLY_YIELD_TRIGGER_SECONDS := 0.2
const CELL_BUCKET_SIZE := 4.0
const OCCUPY_CELL_SPAN := 2
const SLOT_SEARCH_RADIUS := 32
const SWAP_COOLDOWN_TICKS := 10
const PARKING_GAP_CELLS := 1
const ROUTE_LANE_COMFORT_RADIUS_FACTOR := 0.4
const MAX_CATCH_UP_TICKS := 2
const REROUTE_BUDGET_PER_TICK := 8
